/**
 * Column allowlists for the DEMO-1a copy step.
 *
 * The spec's rule: "When copying a table, copy only an explicit allowlist
 * of columns; null out anything free-text." These lists are the single
 * source of truth for what is allowed to cross from a live Alcan row into
 * the demo org. Anything not listed here is either replaced with a fresh
 * demo-authored value (name, email, ids) or left at its column default.
 *
 * `assertNoFreeTextLeak` is a standing regression guard, exercised in
 * columnAllowlist.test.ts: if a future edit ever adds one of the known
 * free-text columns to an allowlist by mistake, the test suite fails loudly
 * instead of silently shipping a name/note leak.
 */

// ---------------------------------------------------------------------------
// staff
// ---------------------------------------------------------------------------

/**
 * Structural columns copied from a source staff row. Deliberately excludes
 * name, email, user_id (identity -- replaced from the cast list), and any
 * admin/super-admin flag (never granted by the copy; only the three named
 * demo logins get elevated flags, applied separately in lib/anonymize.ts).
 */
export const STAFF_COPY_ALLOWLIST = [
  'role_id',
  'hire_date',
  'is_coach',
  'is_doctor',
  'is_lead',
  'is_office_manager',
  'is_participant',
  'participation_start_at',
] as const;

/**
 * Columns on `staff` that hold free text (or are otherwise identity-shaped)
 * and must never be copied. `location` / `organization` are legacy plain-
 * text fields (distinct from the FK columns `primary_location_id` /
 * `organization_id`) that have held real, human-typed location/org names in
 * the past -- excluded on that basis alone.
 */
export const STAFF_FREE_TEXT_COLUMNS = [
  'name',
  'email',
  'location',
  'organization',
  'home_route',
  'scheduling_link',
  'pause_reason',
  'baseline_released_by',
] as const;

// ---------------------------------------------------------------------------
// weekly_assignments
// ---------------------------------------------------------------------------

/**
 * `source` is deliberately not in this list: the seed script always stamps
 * every copied row's `source` as `'demo-seed'` (see
 * lib/rowBuilders.ts#buildDemoAssignmentDraft), it never carries the
 * original value (e.g. `'sequencer'`, `'onboarding'`) through.
 */
export const WEEKLY_ASSIGNMENTS_COPY_ALLOWLIST = [
  'role_id',
  'week_start_date',
  'display_order',
  'action_id',
  'competency_id',
  'status',
  'self_select',
] as const;

/**
 * `ai_rationale` is a free-text sentence generated by sequencer-auto-assign
 * ("team confidence is low for this skill" style copy plus, historically,
 * some runs that echoed staff-specific context) -- excluded defensively.
 */
export const WEEKLY_ASSIGNMENTS_FREE_TEXT_COLUMNS = [
  'ai_rationale',
] as const;

// ---------------------------------------------------------------------------
// weekly_scores
// ---------------------------------------------------------------------------

export const WEEKLY_SCORES_COPY_ALLOWLIST = [
  'confidence_score',
  'confidence_date',
  'confidence_late',
  'performance_score',
  'performance_date',
  'performance_late',
  'week_of',
] as const;

/** weekly_scores has no free-text columns today; listed for completeness. */
export const WEEKLY_SCORES_FREE_TEXT_COLUMNS = [] as const;

// ---------------------------------------------------------------------------
// Tables that must never be copied at all, per the spec's "never copies"
// list. Not consulted by the column-pick helpers below -- the orchestrator
// simply never queries these tables for the source location. Kept here so
// there is one place that documents the full list, and so a test can assert
// none of them appear in any *_COPY_ALLOWLIST export in this module.
// ---------------------------------------------------------------------------

export const NEVER_COPY_TABLES = [
  'evaluations',
  'evaluation_items',
  'coaching_sessions',
  'coaching_session_selections',
  'coaching_meeting_records',
  'coaching_agenda_templates',
  'coach_baseline_assessments',
  'coach_baseline_items',
  'coach_baseline_audit',
  'doctor_baseline_assessments',
  'doctor_baseline_items',
  'staging_prompts',
  'reminder_log',
  'admin_audit',
  'staff_audit',
  'survey_responses',
] as const;

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/**
 * Returns a new object containing only the keys in `allowlist` that are
 * present on `row`. Anything not in `allowlist` is dropped, never copied
 * through by accident (e.g. by a future column rename or a careless
 * `...row` spread elsewhere in the script).
 */
export function pickAllowedColumns<T extends object>(
  row: T,
  allowlist: readonly (keyof T & string)[],
): Partial<T> {
  const out: Partial<T> = {};
  for (const col of allowlist) {
    if (Object.prototype.hasOwnProperty.call(row, col)) {
      out[col] = row[col];
    }
  }
  return out;
}

/**
 * Throws if any column in `allowlist` also appears in `freeTextColumns`.
 * Call this once per table allowlist at module load (or in a test) so a
 * mistaken addition fails fast instead of quietly shipping a name/note leak.
 */
export function assertNoFreeTextLeak(
  allowlist: readonly string[],
  freeTextColumns: readonly string[],
): void {
  const leaked = allowlist.filter((c) => (freeTextColumns as readonly string[]).includes(c));
  if (leaked.length > 0) {
    throw new Error(
      `Column allowlist includes free-text column(s), refusing to copy: ${leaked.join(', ')}`,
    );
  }
}
